### ISSUE TITLE
vqt_evalの指定範囲にレコードがないと落ちる

### ISSUE THREAD

**Issue by hinoshiba** [vouquet/vouquet#49]
```
$ ./vqt_eval -c vouquet.conf 2021/02/01 2021/02/10 BTC2JPY_mgn coinzcom 0.01
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.eval(0x0, 0x0)
        /go/src/src/vouquet/exec/vqt_eval/vqt_eval.go:98 +0x132a
main.main()
        /go/src/src/vouquet/exec/vqt_eval/vqt_eval.go:215 +0x26
```

**Comment by hinoshiba** [comment]
対応完了
